### ISSUE TITLE
Desktop Widget Support

### ISSUE THREAD

**Issue by mantree** [Zren/plasma-applets#11]
This widget is exactly what I'm looking for! There's just one problem :)

When I create the widget it is a small box, blank, the time is not shown. Then when I configure it the widget grows to be extremely wide! It also won't let me resize it back down to a sensible size.

Obviously this is isn't really a problem with the widget as such, just something isn't playing right quite right. This is on a fresh installation of Antergos. I can't find any kind of logs for this stuff.

Any ideas on where I might be able to find some information to help?

**Comment by Zren** [comment]
You're talking about the clock being extremely wide in the panel right? How wide is you're panel. Got any screenshots?

**Comment by mantree** [comment]
No, i'm not adding the widget to a panel.

![screenshot_20160411_173243](https://cloud.githubusercontent.com/assets/422106/14434587/86b0c830-000b-11e6-94ae-5673ad418c3a.png)

![screenshot_20160411_173307](https://cloud.githubusercontent.com/assets/422106/14434601/9fd3a5ee-000b-11e6-96d8-1027a98d8a17.png)

I might be misunderstanding how to use these things.

**Comment by mantree** [comment]
If I add it to a panel, it seems to do a similar thing and fill the whole thing up.

**Comment by Zren** [comment]
Ahhhh, you're using it as a desktop widget.

But it shouldn't be doing that in the panel (it IS suppose to scale to the height of the panel (or width if using a vertical panel).

What version of kde + distro?

**Comment by mantree** [comment]
![screenshot_20160411_174637](https://cloud.githubusercontent.com/assets/422106/14434943/5c041d10-000d-11e6-8f7f-7e092bf201ae.png)

Ah, so is using it as a desktop widget not recommended :)

**Comment by Zren** [comment]
For now yeah, I'll see about supporting it later on.

**Comment by Zren** [comment]
Another user interested in desktop widget: http://kde-look.org/content/show.php?content=175591&forumpage=2#c487238

I'll be adding slightly terrible support for desktop applet by forcing the desktop applet to use the popup view which contains the calendar. This is probably the main reason people would use it anyway since there are other (probably better) applets for a clock.

I'll see about properly scaling the background of the widget later once I fix all the hardcoded pixel sizes  throughout my code so I can scale the widget nicely.

You can resize the background + turn off widgets to make the default (top) look like the bottom.

![](https://i.imgur.com/MywExHm.png)

**Comment by Zren** [comment]
Proper widget scaling will be in v33, released sometime tonight.
