### ISSUE TITLE
[EventCalendar] Akonadi / KDE Calendar Plugins Sync

### ISSUE THREAD

**Issue by bugzy** [Zren/plasma-applets#12]
Is there any chance of adding sync to caldav resources instead of just google calendar? The source code of the following projects may be of help to implement such a function:
-Google Calendar Agenda [1]
-Akonadi Calendar, Contacts, and Tasks [2]

[1] https://github.com/gjedeer/gcal-plasmoid 
[2] https://quickgit.kde.org/?p=akonadi-google-applets.git&a=tree&hb=e381b18168d190a370d34350fe33fc10319b1091

**Comment by Zren** [comment]
This is unlikely to happen. Especially not before the default applet supports it through Kontact. I really don't want to write a caldav parser, then try to build an abstract layer on top of the google calendar models to support it.

**Comment by Zren** [comment]
Repurposing this issue for synching to the KDE Plasma calendar plugin for KDE PIM which uses Akonadi.

#57 will be for syncing an .ics without Akonadi py parsing/modifying the .ics files manually.

**Comment by danvratil** [comment]
You can check the current Digital Clock applet plugin that provides integration with Akonadi calendar. The code is here: https://cgit.kde.org/kdepim-addons.git/tree/plugins/plasma/pimeventsplugin - most of the code should be reusable for your purpose.

**Comment by Zren** [comment]
Pinging @renyuneyun since he hasn't subscribed to this issue yet.

I've managed to implement showing the KHolidays plugin.

https://github.com/Zren/plasma-applet-eventcalendar/commit/335b7b0515b043f6c0a9248e6538030d4c46e42e

![](https://i.imgur.com/FHlQcGb.png)

Right now it's hardcoded to point to the holidays plugin only.

I still need to add the config ui from digitalclock. Right now you can't select the region the holiday events are from without opening up digital clocks settings (the selection is saved to `~/.config/plasma_calendar_holiday_regions`). I'd like to be able to have the plasma events plugins automatically selected by default, but might be more hassle than it's worth.

I'm going to need to figure out if I need to either bump the minimum plasma version for this feature. It'd be a hassle to use a `Loader {}` pattern where it fails gracefully if the events API is missing.

The most annoying part is probably that I'll need to install akonadi + PIM once I've finished the KHolidays config UI so I can test that.

**Comment by Zren** [comment]
I've tested the holidays plugin, but you should be able to enable the KDE PIM plugin too from the generic new "Events" tab.

![](https://i.imgur.com/RbWIxGp.png)

Gonna fire up a VM and install KDE PIM.

If you'd like to test yourself try the git master using:  
https://github.com/Zren/plasma-applet-eventcalendar#update-to-github-master

**Comment by Zren** [comment]
v54 released. Tell me if there's any issues with Kontact integration.

**Comment by bugzy** [comment]
Working great. Thanks

**Comment by renyuneyun** [comment]
Works great :+1: Thanks a lot.

Only one feature lacking: using the color from KOrganizer :P

**Comment by Zren** [comment]
Does the color show up in digitalclock? I though I was using the color provided by the plasma plugin.

**Comment by danvratil** [comment]
The Plasma plugin reads the colors from Akonadi Collection attributes and falls back KOrganizer settings otherwise, the relevant code is here: https://github.com/KDE/kdepim-addons/blob/master/plugins/plasma/pimeventsplugin/akonadipimdatasource.cpp#L74

**Comment by Zren** [comment]
Hmmm, whoops. It appears I never bothered reading the `CalendarEvents::EventData::eventColor()`/`dayItem.eventColor` since it was an empty string for KHolidays.

* https://github.com/Zren/plasma-applet-eventcalendar/blob/master/package/contents/ui/calendars/PlasmaCalendarManager.qml#L123

I'll get right on that then.

Leaving some other links here for reference later.

* https://github.com/KDE/kdepim-addons/blob/master/plugins/plasma/pimeventsplugin/eventdatavisitor.cpp#L196
* https://github.com/KDE/kdeclarative/blob/master/src/calendarevents/calendareventsplugin.h#L147

**Comment by Zren** [comment]
@renyuneyun, does the git master work?

https://github.com/Zren/plasma-applet-eventcalendar#update-to-github-master

**Comment by renyuneyun** [comment]
It doesn't seem to work. All the colors are still the default one.

By the way, there is another bug: some duplicated entries (but not all entries have duplication) will be listed in the calendar after refresh. It may be related to "refresh", or something else (I remember last time each "fresh" I click, some duplications were created; but this time I only get 2 instances, i.e. 1 duplication).
Maybe you forgot to clear the list/vector (or something similar) after reloading?

**Comment by brainode** [comment]
@Zren Where i can find you PayPal info? Want to send you few $.

**Comment by bugzy** [comment]
Thanks for taking care of this
