### ISSUE TITLE
Duplicate events when using wholeday feature

### ISSUE THREAD

**Issue by schmaker** [Zren/plasma-applets#14]
Screenshot is pretty self-explaining i guess. The event should take just one day instead of two.
![plasma1](https://cloud.githubusercontent.com/assets/14954032/14583114/6c7d55da-0418-11e6-9986-8d0ba77b7a17.png)

**Comment by Zren** [comment]
What locale are you using?

**Comment by schmaker** [comment]
cs-CZ if it matters                                                                                                                                                                                                                                                                                                                                        Odesláno ze smartphonu se systémem BlackBerry 10.                                                                                                                                                                                                                Od: Chris HollandOdesláno: neděle, 17. dubna 2016 3:08Komu: Zren/plasma-appletsOdpovědět: Zren/plasma-appletsKopie: schmakerPředmět: Re: [Zren/plasma-applets] Duplicate events when using wholeday feature (#14)What locale are you using?

—You are receiving this because you authored the thread.Reply to this email directly or view it on GitHub

**Comment by Zren** [comment]
Just had a fear that new days might start at a time other than midnight in your locale for some reason, but that doesn't make any sense even with that assumption.

It reminded me of this: http://infiniteundo.com/post/25326999628/falsehoods-programmers-believe-about-time

> many oddities of which I wasn’t aware. For instance: in the Jewish calendar, days start at sunset not midnight.

Though this (or #17) is probably related to me parsing `dateTime = new Date(event.start.date + '00:00:00')` somehow. I just know it. Anyways, I should probably get to coding instead of issue handling.

**Comment by Zren** [comment]
So ya, this was a bug introduced when I added the performance fix to clip for events with really long durations. The upper limit changed to an inclusive check when it needs to be an exclusive usually.

Fixed in https://github.com/Zren/plasma-applets/commit/d644cb9aac407d1994538c9e31b3699aa9502641

Will be in v28
