### ISSUE TITLE
Pin to stop hiding the calendar

### ISSUE THREAD

**Issue by schmaker** [Zren/plasma-applets#15]
Little bit annoying thing i found while working with plasmoid was, that it keep disappearing after clicking away. That behavior is pretty much okay, but pin lock would be handy to keep it on the top of other windows.

**Comment by Zren** [comment]
So people actually used that. Huh. Okay then. Hmm. I'd have to add back the padding around the popup too.

**Comment by schmaker** [comment]
I just installed the plasmoid, haver no idea it was there earlier :)There are scenarios where it can be pretty handy though                                                                                                                                                                                                                                                                                                                                        Odesláno ze smartphonu se systémem BlackBerry 10.                                                                                                                                                                                                                Od: Chris HollandOdesláno: neděle, 17. dubna 2016 3:12Komu: Zren/plasma-appletsOdpovědět: Zren/plasma-appletsKopie: schmakerPředmět: Re: [Zren/plasma-applets] [Feature request]Pin to stop hiding the calendar (#15)So people actually used that. Huh. Okay then. Hmm. I'd have to add back the padding around the popup too.

—You are receiving this because you authored the thread.Reply to this email directly or view it on GitHub

**Comment by Zren** [comment]
I had to add padding around the popup to implement this. The padding isn't needed when the timer is enabled, but it's deffinitely needed if neither widget is enabled otherwise it'll overlay the "Next Month" button. I might overlay the pin on top of the meteogram when it's just that enabled. We'll see.

![](https://i.imgur.com/chJopYd.png)
![](https://i.imgur.com/1tVw1Zu.png)
![](https://i.imgur.com/UtRyHMV.png)

Added in v33, released sometime tonight.
