### ISSUE TITLE
[volumewin7mixer] Doesn't resizeable the popup window

### ISSUE THREAD

**Issue by kikadf** [Zren/plasma-applets#21]
Hi!
I use volumewin7mixer, with glassified theme, on my kde5. (workspace-5.6.3; kf-5.21.0)
If I use more apps with sound, I can't look all on the popup window, because it isn't resizeable.

I test with breeze, and oxygen theme, same problem. I read that you test only 5.5, but do you plan upgrade your kde, or can you check this problem?

<blockquote class="imgur-embed-pub" lang="en" data-id="9HExVad"><a href="//imgur.com/9HExVad">View post on imgur.com</a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

**Comment by Zren** [comment]
That's what it can look like in 5.5 too. It's not supported for use in the systray (I should probably remove the metadata flag for that). Do you know of _any_ applet that can resize the systray popup container? Because if not, then this won't be able to be fixed. This is probably the reason why the default mixer is horizontal.

I could make it horizontally scrollable (ew). I technically should do that anyway in case someone fill it up in a low res narrow screen.

It also looks like the volume slider's have no appearance in that theme? Bleh. Do sliders normally just show up with the handle in that theme? I didn't draw the handle since I thought the groove would be enough. Blarg.

**Comment by kikadf** [comment]
The volume sliders is appearance in other theme, like breeze or oxygen, so it is a glassified theme issue.
I didn' see any applet in kde5 what can resize the popup window.... just saw horizontally scroll...

**Comment by Zren** [comment]
If you never have it hidden, you might as well just add it to your panel. It popup will resize (up to the width of your screen hopefully). You'll have to turn it manually remove it from the systray for now though `SysTray Settings > General > Extra Items > Uncheck Audio (Win7)`.

Looks like the [width is forced](https://github.com/KDE/plasma-workspace/blob/master/applets/systemtray/package/contents/ui/items/PlasmoidItem.qml#L52) so there isn't a way to resize it in the systray. So I definitely will be removing it from the systray.

As for glassified, it's more an issue that I don't draw the handles (this is what it looks like when I draw them). I just didn't think there we themes that didn't draw a groove.

![](https://i.imgur.com/ziBACH1.png)

If I go back to drawing it norammly and also draw the tickmarks (with 15 steps) it'll look like:

![](https://i.imgur.com/8t67Axv.png)
![](https://i.imgur.com/ghDyJwc.png)

Maybe I could enforce using the breeze theme slider for this somehow. I was hoping to draw the current "volume" in the background like Windows 7, but I have no idea how to do that (and no one else has done it yet either).

**Comment by Zren** [comment]
So I decided to manually style the slider entirely. I want to have ticks every 10%, and wider ticks at 0%, 50%, and 100%.

Glassified > Breeze Dark > Breeze Light

![](https://i.imgur.com/LAp5XYI.png)
![](https://i.imgur.com/7FWMGRv.png)
![](https://i.imgur.com/sAWPxei.png)

Getting a visible tick color in all themes caused me no end of pain with glassified using pure white for nearly everything because it uses images to "darken" the background. Decided to just do `color: theme.textColor == theme.buttonBackgroundColor ? theme.backgroundColor : theme.textColor`.
