### ISSUE TITLE
[TodoList] No icon displayed

### ISSUE THREAD

**Issue by vmorenomarin** [Zren/plasma-applets#32]
Hi, excellent widget. You have great ideas. 

After the installation and have restarted Plasmashell because there was a issue with the width of the widget. This was solved easily. But the icon it's no showed in the panel. Any suggestion?

I run Desktop: KDE Plasma 5.7.4 (Qt 5.7.0) on Chakra OS.

![image](https://cloud.githubusercontent.com/assets/13444664/18152668/2fe23f30-6fbd-11e6-91bd-4fd9550328c7.png)

**Comment by Zren** [comment]
Odd, I thought it was a standard icon (`view-list-symbolic`). Does it show the icon when you add the widget? If not, what icon theme are you using? Breeze?

![](https://i.imgur.com/Yp8DCrY.png)

**Comment by vmorenomarin** [comment]
The  icon theme is not Breeze, the desktop theme yes. I will try with Breeze icon theme. 

When I add the widget there is not displayed icon.

**Comment by Zren** [comment]
Did using breeze icons fix it? What theme were you using before if so?

**Comment by vmorenomarin** [comment]
Hi. I use Antü icon theme. I did solve the issue copyng a similar icon as `view-list-symbolic`. Then, TodoList looks like: 

![image](https://cloud.githubusercontent.com/assets/13444664/18324421/042cfe30-7502-11e6-88dc-84c598889c2b.png)

The original name of the icon is `view-list-details`.

**Comment by Ciul** [comment]
Please fix this.

**Comment by Zren** [comment]
While I could try finding an icon that plays nice with **every** icon theme, it'd be a pain to find a good icon since a lot inherit from Gnome's humanity instead of KDE's Breeze.

If you're using Antu, open `~/.local/share/icons/Mac iOS/index.theme` and change `Inherits=Humanity,gnome,hicolor` to `Inherits=breeze,hicolor`. Then relog to apply it.

I could try shipping the breeze icon with the plasmoid, but I don't think it would follow the colour scheme.

**Comment by Zren** [comment]
Icon can now be configured in the next version.
