### ISSUE TITLE
Volume applet: use description instead of name for mixer item labels

### ISSUE THREAD

**Issue by AndydeCleyre** [Zren/plasma-applets#33]
Firstly, thank you for your awesome contributions. Your event (+ weather) calendar, volume applet, and thumbnail grid task switcher are fantastic.

For the mixer items (aside from the specially handled Mic/Speaker/HDMI/appName items), it seems more natural to me to use the Description, rather than the Name, for the label. I don't have many audio devices to test with, though.

In my case it's the difference between `bluez_sink.xx_xx_xx_xx_xx_xx` and `Fluance Fi50`

**Comment by Zren** [comment]
Ah good point. I [added aliases](https://github.com/Zren/plasma-applets/blob/master/org.kde.plasma.volumewin7mixer/package/contents/ui/MixerItem.qml#L74) for `alsa_output.pci-0000_00_14.2.analog-stereo` => `Speaker`, and `alsa_output-0000_01_00.1.hdmi-stereo` => `HDMI` since I assumed that was the common pattern.

~~Is bluez a default audio driver (that I should simplify with an alias as "Speaker") or just use the description?~~ It seems to be a bluetooth headset, so we definitely should use the description.

**Comment by AndydeCleyre** [comment]
My device here is a bluetooth speaker, but yeah just calling it "Speaker" wouldn't clarify that it's different from my laptop's speakers+headphones mixer item ("Speaker").

**Comment by Zren** [comment]
It should use the description in v14.

**Comment by AndydeCleyre** [comment]
That looks much better, thanks!
