### ISSUE TITLE
Shows applications before desktop search

### ISSUE THREAD

**Issue by danielmaurer** [Zren/plasma-applets#55]
In search shows applications before desktop search, or create an option for to select the search order.

**Comment by Zren** [comment]
Are you using the kde5.5 version? Newer versions uses the same search order as Application Launcher.

**Comment by danielmaurer** [comment]
I'm using the kde 5.8.5 version. When I search for an application name that has a folder with as same name shows the folder first, diferent of the Application Launcher that shows the application first.

**Comment by Zren** [comment]
`grep Version ~/.local/share/plasma/plasmoids/com.github.zren.tiledmenu/metadata.desktop` show's what version?


You should already have the option to have a [category view since v7](https://github.com/Zren/plasma-applets/blob/master/tiledmenu/Changelog.md#v7---november-26-2016).
![](https://i.imgur.com/ZKTSW70.png)

**Comment by danielmaurer** [comment]
Shows version 10 and the option Search Result is setted how Merged.

**Comment by danielmaurer** [comment]
I reinstalled and now its works fine.
