### ISSUE TITLE
How can I move the days column?

### ISSUE THREAD

**Issue by phyrz91** [Zren/plasma-applets#63]
I can not move the days column to the left when Local Weather is disabled.
Any Idea? 

https://postimg.org/image/vaajerx93/

**Comment by Zren** [comment]
I've thought about hiding the weather column before when you months other than the current one, but figured the consistent placement would be best (an excuse my lazyness accepted).

The android app [Event Flow Calendar](https://play.google.com/store/apps/details?id=com.syncedsynapse.eventflowwidget&hl=en) which this is based on places the weather on the right side. When I wrote this though, I didn't know how to make the center column "fill" the width, so I placed it on the left. I actually prefer it on the left now because it's right next to the date.

This looks okay, so I guess I commit it. http://streamable.com/0qn65

**Comment by Zren** [comment]
v41 with this is released

**Comment by phyrz91** [comment]
Thx a lot!
