### ISSUE TITLE
Event Calendar doesn't use the right scaling

### ISSUE THREAD

**Issue by sudhirkhanger** [Zren/plasma-applets#66]
As you can see in the screenshot below all plasma widgets are of particular size but event calendar is almost double the size. I am on 1920x1080p screen with 141dpi.

![screenshot_20170303_184458](https://cloud.githubusercontent.com/assets/841656/23552457/f280f8d2-0041-11e7-8d4c-b1bb6468cdcd.png)
![screenshot_20170303_184519](https://cloud.githubusercontent.com/assets/841656/23552458/f282914c-0041-11e7-9625-4934c737d6c7.png)

**Comment by Zren** [comment]
141dpi sounds a bit weird, mostly because 96 dpi is the default. Double would be 192. 1.5x would be 144.

Every other widget uses a multiple of `units.gridUnit` which is apparently [based off the text height or something](https://github.com/KDE/plasma-framework/blob/master/src/declarativeimports/core/units.cpp#L245)? Font scaling is usually jumpy.
I'm using `units.devicePixelRatio` which is based on your just your dpi.

You can edit PopupView.qml at `/home/chris/.local/share/plasma/plasmoids/org.kde.plasma.eventcalendar/contents/ui/PopupView.qml` and change the minimum height if you like. This line right here is what you need to change for the width (https://github.com/Zren/plasma-applets/blob/master/org.kde.plasma.eventcalendar/package/contents/ui/PopupView.qml#L33). The height is set [here under bottomRowHeight](https://github.com/Zren/plasma-applets/blob/master/org.kde.plasma.eventcalendar/package/contents/ui/PopupView.qml#L22).

Run `killall plasmashell; kstart5 plasmashell` to reload the panel with your changes.

**Comment by Zren** [comment]
Edited previous comment, you need to change the preferredWidth not the minimumWidth

**Comment by sudhirkhanger** [comment]
I got the dpi from the dpi.lv website.

![Uploading Screenshot_20170303_202159.png…]()

**Comment by Zren** [comment]
I actually forgot I made it a bit larger than the default widgets. I wouldn't call it double the size though.

![](https://i.imgur.com/ZJuys3Y.png)

At 141 DPI, it's still not much bigger.

![](https://i.imgur.com/B5tIyvd.png)

Does it really need to be the same size? The smaller I make it, the less items are visible in the agenda usually shown on the left.

**Comment by Zren** [comment]
Though I guess I could make it the same size as default when all the other widgets aren't visible.

**Comment by Zren** [comment]
Popup w/o Agenda is Width/Height is 378px.
Without the padding around the calendar, it's 342px.
When the agenda is added, the width of the calendar is 351px while the height is still 342px.
So I'll chose 342px.

This will be in the next version. I'll probably release in tonight or tomorrow. I'll close the issue when it's released.

![](https://i.imgur.com/3ON969l.png)

**Comment by Zren** [comment]
Added in v43
